- wbce/templates/advancedThemeWbFlat/theme.css
These changes were overwritten incidentally by my last commit.
> Allow the content area of advancedThemeWbFlat to be responsive.

- wbce/modules/mod_opf_auto_placeholder/install.php
- wbce/modules/mod_opf_csstohead/install.php
- wbce/modules/mod_opf_droplets/install.php
- wbce/modules/mod_opf_email/filter.php
- wbce/modules/mod_opf_email/index.php
- wbce/modules/mod_opf_email/info.php
- wbce/modules/mod_opf_email/install.php
- wbce/modules/mod_opf_email/languages/DA.php
- wbce/modules/mod_opf_email/languages/DE.php
- wbce/modules/mod_opf_email/languages/EN.php
- wbce/modules/mod_opf_email/languages/FR.php
- wbce/modules/mod_opf_email/languages/NL.php
- wbce/modules/mod_opf_email/languages/NO.php
- wbce/modules/mod_opf_email/languages/RU.php
- wbce/modules/mod_opf_email/precheck.php
- wbce/modules/mod_opf_email/templates/output_filter.tpl.php
- wbce/modules/mod_opf_email/tool.php
- wbce/modules/mod_opf_email/uninstall.php
- wbce/modules/mod_opf_email/upgrade.php
- wbce/modules/mod_opf_insert/install.php
- wbce/modules/mod_opf_short_url/install.php
- wbce/modules/mod_opf_sys_rel/install.php
- wbce/modules/mod_opf_sys_rel/upgrade.php
- wbce/modules/mod_opf_wblink/install.php
- wbce/modules/outputfilter_dashboard/edit_filter.php
- wbce/modules/outputfilter_dashboard/tool.php
- wbce/modules/outputfilter_dashboard/upgrade.php
merged Norhei's fixes into my branch
take settings into account when displaying if filter is active
use integer value for active state in install scripts
> opf and filter modules: fix active/inactive

- wbce/templates/argos_theme_reloaded/css/theme.css
- wbce/templates/argos_theme_reloaded/patch/page_tree.php
bad habit, to use short_open_tag ... sorry
> Hopefully fixed # 223

- wbce/modules/settings_defaults/templates/tool.tpl.php
- wbce/modules/settings_general/templates/general.tpl.php
- wbce/modules/settings_general/tool.php
> Update settings_default and settings_general

- wbce/admin/admintools/tool.php
Calling an admintoo directly whithout being logged in did throw a error message instead of redirecting to login
> Admintool problem

- wbce/framework/class.frontend.php
- wbce/framework/class.settings.php
- wbce/modules/SecureFormSwitcher/install.php
- wbce/modules/SecureFormSwitcher/tool.php
- wbce/modules/SecureFormSwitcher/uninstall.php
- wbce/modules/maintainance_mode/info.php
- wbce/modules/maintainance_mode/tool.php
maintainance mode did not work properly plus found a bug in settings class which had problems whith php type juggling
> Maintainance mode fixes

- wbce/templates/argos_theme_reloaded/templates/header.htt
- wbce/templates/wbce_flat_theme/templates/header.htt
This is not allowed in html !
O
> No Comments or other stuff allowed before Doctype declaration.

- wbce/modules/wbstats/backend.css
- wbce/modules/wbstats/class.count.php
- wbce/modules/wbstats/info.php
- wbce/modules/wbstats/initialize.php
- wbce/modules/wbstats/languages/DE.php
- wbce/modules/wbstats/upgrade.php
#306 there are some minor changes to our (old) 0.1.11 version, in this case the changes (from our 0.1.12 release) with the non-functional $Referer are removed
> replace visitor statistics with 0.1.11 version from developer repository

- wbce/admin/pages/modify.php
- wbce/templates/argos_theme_reloaded/templates/pages_modify.htt
- wbce/templates/wbce_flat_theme/templates/pages_modify.htt
Check this out for more info: 
https://forum.wbce.org/viewtopic.php?pid=15033#p15033
> Added page section modify.phps as template vars.

- wbce/admin/pages/modify.php
Disable removing of unknown vars to prevent the deleting of JavaScript arrays [] or {}
More:
https://forum.wbce.org/viewtopic.php?pid=15181#p15181
> Disable removing of unknown vars

- wbce/modules/output_filter/filter_routines.php
symptom: when filling in a form users get redirected to the home page and the data entered is not processed: There are no notification mails to the site owner nor the data ends up in the submission table, see https://forum.wbce.org/viewtopic.php?id=1722
> fix mpform problem with WBCE 1.3

- wbce/include/phplib/template.inc
Replaced while/each to foreach and preg_replace with str_replace where possible. Now the template engine can handle variables with larger strings with a faster processing time.
Fixed #327 
Thanks to the WBCE community!
> Tweaked for better performance

- wbce/framework/class.login.php
Refactored. each() is deprecated in PHP 7.2
> Refactored each()

- wbce/framework/functions-utf8.php
Refactored. create_function() is deprecated in PHP 7.2
> Refactored create_function()

- wbce/modules/show_menu2/include.php
Since we now have the is_countable() polyfill function, let's apply it right away.
Also, one of the code code sequences was inserted twice as reported by Colinax.
> apply is_countable() instead of is_array()

- wbce/modules/show_menu2/include.php
SM2_CORRECT_MENU_LINKS check corrected
some minor syntax changes in SELECT queries etc..
>  SM2_CORRECT_MENU_LINKS check corrected

- wbce/account/functions/functions.php
- wbce/account/login_form.php
- wbce/framework/functions.php
- wbce/modules/show_menu2/include.php
- wbce/modules/sitemap/view.php
@Colinax 
Please check the following functions (/framework/functions.php) before merging:
- load_language()      // when installing a language
- load_template()       // when installing a template
- load_module()         // when installing a module
- upgrade_module()  // when upgrading a module
- delete_page()          // when deleting a page
I have apllied the $database->updateRow(), insertRow() and delRow() methods to these functions.
> Making use of lately included DB functions & clean up

- wbce/framework/functions.php
All the functions in this file got their own comments.
Also some more clean up for better readybility of code.
> Add comments to all the functions in functions.php

- wbce/modules/menu_link/modify.php
https://github.com/WBCE/WBCE_CMS/issues/366
> Handle issue #366

- wbce/framework/I.php
- wbce/framework/Insert.php
- wbce/framework/initialize.php
- wbce/framework/wsession.php
- wbce/modules/output_filter/filter_routines.php
- wbce/modules/output_filter/filters/filterGeneratePlaceholders.php
Bring back NorHei's Insert Class and make use of the (PH) Placeholders as hooks for this class.
Also in this commit: rework the framework/initialize.php: get rid of constants that have been defined but have never been used.
>  Implementation of class Insert and all necessary components

- wbce/framework/frontend.functions.php
- wbce/modules/droplets/tool.php
replace create_function() function as it is deprecated in newer PHP versions.
> handling of PHP > 7.0.0. compatibility issues

- wbce/modules/menu_link/save.php
- wbce/modules/show_menu2/classes/sm2_formatter.php
- wbce/modules/show_menu2/include.php
German thread for this issue:
https://forum.wbce.org/viewtopic.php?pid=20824#p20824
> Handle issues with SM2_CORRECT_MENU_LINKS

- wbce/modules/droplets/example/SectionPicker.php
- wbce/modules/topics/rss.php
- wbce/modules/topics/view.list.php
see the individual commit messages
> some fixes around topics

- wbce/framework/Insert.php
Handle Class Insert issue which prevented JS and CSS code blocks from displaying correctly
> handle Class Insert issue

- wbce/install/install_struct.sql
For proper use of the _Account and Signups configuration_ Tool (tool_account_settings) which will be implemented with WBCE CMS v. 1.4.0
> Add DB columns to `{TP}users`

- wbce/account/confirm.php
- wbce/admin/groups/index.php
- wbce/admin/login/forgot/index.php
- wbce/admin/pages/delete.php
- wbce/admin/pages/restore.php
- wbce/admin/pages/settings2.php
- wbce/admin/users/index.php
- wbce/framework/Accounts.php
- wbce/framework/functions.php
- wbce/modules/tool_account_settings/account/check_preferences.php
- wbce/modules/tool_account_settings/account/form_forgot.php
- wbce/modules/tool_account_settings/account/form_signup.php
- wbce/modules/tool_account_settings/js/jquery.tablesorter/theme.wbEasy.css
- wbce/modules/tool_account_settings/templates/form_login.twig
- wbce/modules/tool_account_settings/theme/tool_overview.twig
- wbce/modules/tool_account_settings/tool_overview.php
- wbce/templates/argos_theme_reloaded/templates/groups_form.htt
- wbce/templates/argos_theme_reloaded/templates/users_form.htt
- wbce/templates/wbce_flat_theme/templates/groups_form.htt
- wbce/templates/wbce_flat_theme/templates/users_form.htt
Delete access files when visibility changed to 'none'  …
or when page moved to trash
>  Delete access files when visibility changed to 'none'

- wbce/framework/frontend.functions.php
I have re-added  get_section_content() in a separate commit because it is used in the section picker droplet
Yes, there is duplicate code now, so it's perhaps not yet in a state to be merged. Maybe we put the code that is inside of get_section_content() in a separate include file (which is not very elegant either) or we find an even better solution.
>  proposed fix for #417 

- wbce/admin/pages/settings2.php
- wbce/framework/Insert.php
- wbce/framework/class.admin.php
- wbce/framework/class.wb.php
- wbce/framework/frontend.functions.php
- wbce/modules/tool_account_settings/templates/form_forgot.twig
- wbce/modules/tool_account_settings/templates/form_login.twig
- wbce/modules/tool_account_settings/templates/form_preferences.twig
> adding new insert placeholders

- wbce/admin/pages/settings2.php
- wbce/admin/settings/index.php
- wbce/admin/settings/save.php
- wbce/framework/Insert.php
- wbce/framework/class.admin.php
- wbce/framework/class.wb.php
- wbce/framework/frontend.functions.php
- wbce/modules/miniform/modify.php
- wbce/modules/miniform/modify_template.php
- wbce/modules/tool_account_settings/templates/form_forgot.twig
- wbce/modules/tool_account_settings/templates/form_login.twig
- wbce/modules/tool_account_settings/templates/form_preferences.twig
- wbce/templates/argos_theme_reloaded/templates/settings.htt
- wbce/templates/wbce_flat_theme/templates/settings.htt
handle settings issue with multiple id's with the same value  `wbmailer_smtp_auth`
> handle settings issue with multiple id's with the same value

- wbce/framework/Insert.php
There was another issue  w/ MEDIA_DIRECTORY constant that came up in error-logs,
now handled
> Handle "Cache Control" issue reported internally by colinax, florian

- wbce/modules/menu_link/view.php
- wbce/modules/tool_account_settings/templates/Template_Info_DE.txt
- wbce/modules/tool_account_settings/templates/Template_Info_EN.txt
- wbce/modules/wbSeoTool/functions.php
- wbce/templates/argos_theme_reloaded/templates/settings.htt
- wbce/templates/wbce_flat_theme/templates/settings.htt
and another small issue with a variable that was not correctly initialized
> Hanlde issue #462

- wbce/modules/outputfilter_dashboard/functions.php
> OPF fail-safe fix

- wbce/framework/functions.php
- wbce/modules/CodeMirror_Config/initialize.php
- wbce/modules/CodeMirror_Config/tool.php
- wbce/modules/droplets/templates/modify.twig
- wbce/modules/tool_account_settings/templates/Template_Info_DE.txt
- wbce/modules/tool_account_settings/templates/Template_Info_EN.txt
- wbce/modules/tool_account_settings/templates/form_login.twig
- wbce/modules/tool_account_settings/templates/form_signup.twig
- wbce/templates/theme_fallbacks/css/debug_dump.css
The first one is already integrated.
The second pertains to `debug_dump()`
The third one:
Please note: if you can leave out the two *txt files. We don't need to change them.
I referenced the wrong issue number. Should have been #511 (not #512)
> 3 commints

- wbce/admin/modules/install.php
Should fix issue #560 by improving changes done in PR#558
> Fix regarding usage and cleanup of dir temp_unzip
